// Code generated by goctl. DO NOT EDIT.
package types

type TransactionArgs struct {
	From                 []byte `json:"from"`
	To                   []byte `json:"to"`
	Gas                  string `json:"gas"`
	GasPrice             string `json:"gasPrice"`
	MaxFeePerGas         string `json:"maxFeePerGas"`
	MaxPriorityFeePerGas string `json:"maxPriorityFeePerGas"`
	Value                string `json:"value"`
	Nonce                uint64 `json:"nonce"`
	Data                 []byte `json:"data"`
	Input                []byte `json:"input"`
}

type BoolRes struct {
	Flag bool `json:"flag"`
}
